### ISSUE TITLE
how to use themes resources

### ISSUE THREAD

**Issue by mohitcse22** [5-stones/keycloak-email-otp#5]
where to put themes resources

![image](https://github.com/5-stones/keycloak-email-otp/assets/165882737/803df53f-6a8e-4240-85b4-866ebc949f93)
getting this error with keycloak version 24

**Comment by jspizziri** [comment]
@mohitcse22 , currently this plugin has only be tested with keycloak v22. Open to a PR for newer versions. However, keep in mind that BC would need to be maintained. Also, to be cleared, I'm not saying that the error above is due to v24, simply that we currently don't support v24 so you'll need to create either a PR for v24 or a repro in v22 before we take a look at it.

Thanks!

**Comment by jspizziri** [comment]
Closing due to lack of response.
