### ISSUE TITLE
OTP form issues

### ISSUE THREAD

**Issue by kotnikd3** [5-stones/keycloak-email-otp#6]
I have identified three issues with the OTP form:

1. The number of tries is incorrectly displayed as "{0}" in case user submits incorrect code.
2. User can submit an incorrect code infinite number of times regardless of the value set for "Max Retries".
3. The label "<< Back to Login" should be revised to something like "Resend Email", as it triggers the email resend action instead of restarting the login process (like pressing on the icon "Restart login" above on the right side of user's email).

<img width="399" alt="wrong_code" src="https://github.com/5-stones/keycloak-email-otp/assets/9354023/a9b2f18b-7c26-4f92-b931-a86f6aaec66f">  

Tested with Keycloak versions 22.0.5 and 24.0.3 with the following "Authentication steps".

<img width="983" alt="Screenshot 2024-04-17 at 11 26 45" src="https://github.com/5-stones/keycloak-email-otp/assets/9354023/c47f1741-66c0-4c8e-9ec3-7df19ebdb917">

**Comment by jspizziri** [comment]
@kotnikd3 thanks for the report and documentation!

Happy to review a PR if you want to send it my way. Otherwise, you'll probably have to sit tight for a bit.

I think the UI I'd like to see would be a "Resend Code" in addition to a more obvious "Restart Login" button. Both of those should probably appear below the submit button and be plain hyperlinks or something.

**Comment by kotnikd3** [comment]
@jspizziri Can  give me permissions to create a PR in your repository or should I fork it?

**Comment by jspizziri** [comment]
@kotnikd3 , please fork and submit a PR from your fork.

**Comment by kotnikd3** [comment]
@jspizziri Done in https://github.com/5-stones/keycloak-email-otp/pull/7
